print('                       m')
print('   $m                mm            m')
print('    "$mmmmm        m$"    mmmmmmm$"')
print('          """$m   m$    m$""""""')
print('        mmmmmmm$$$$$$$$$"mmmm')
print('  mmm$$$$$$$$$$$$$$$$$$ m$$$$m  "    m  "')
print('$$$$$$$$$$$$$$$$$$$$$$  $$$$$$"$$$')
print(' mmmmmmmmmmmmmmmmmmmmm  $$$$$$$$$$')
print(' $$$$$$$$$$$$$$$$$$$$$  $$$$$$$"""  m')
print(' "$$$$$$$$$$$$$$$$$$$$$ $$$$$$  "      "')
print('     """""""$$$$$$$$$$$m """"')
print('       mmmmmmmm"  m$   "$mmmmm')
print('     $$""""""      "$     """"""$$')
print('   m$"               "m           "')
print('                       "')
